author: Lauren Bodnar
title: Lauren Bodnar | Blog
subtitle: Wife, Mom, Developer, Maintainer Of Everything
url: /
root: /

# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
 - tagcloud
# - archive
theme: 'diaspora'
# widget behavior
archive_type: 'monthly'
show_count: false

theme_config:
  welcome_cover: /img/cover.jpg
  menu:
    Test: /2019/03/06/hello-world/
    GitHub: https://github.com/laurenbodnar
    Archives: /archives
  social:
    Github: https://github.com/laurenbodnar
    About: /About

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

deploy:
  type: git
  repo: git@github.com:laurenbodnar/laurenbodnar.com.git  #https://bitbucket.org/JohnSmith/johnsmith.bitbucket.io
  branch: gh-pages #published
  #message: [message]  #leave this blank
